### ISSUE TITLE
Support for HTML special chars in card name

### ISSUE THREAD

**Issue by fklemme** [mpaulweeks/mtgify#11]
Hi. I want to use your tool in my wordpress site. It works just fine as long as the card name doesn't contain an apostrophe. I believe the problem is that wordpress converts all special chars to HTML number codes.

These are my problematic cases
`<auto-card>Jace&#8217;s Phantasm</auto-card>`
`<auto-card>Uro, Titan of Nature&#8217;s Wrath</auto-card>`
on https://www.florianklemme.de/index.php/2020/05/01/mill-them-or-kill-them/

I know that this is probably not a problem on your side, nevertheless it would be nice if I could use your program. So do you have an idea for a workaround or is this even something that could be implemented in the code?

I'm using scryfall as the image source. I tried just skipping the apostrophe in the card name, I also tried using the name attribute explicitly. No success, unfortunately.

**Comment by mpaulweeks** [comment]
Interesting! Should be a simple thing to support. Let me look into it this weekend and get back to you.

**Comment by mpaulweeks** [comment]
Fix has been verified via URL you provided.

**Comment by fklemme** [comment]
Thanks! Unfortunately, `<auto-card>Uro, Titan of Nature&#8217;s Wrath</auto-card>` is still broken. Jace's Phantasm works fine, though.

**Comment by mpaulweeks** [comment]
There was a bug in my MtgJson handler and it was missing a few recent sets. Should be fixed now.

**Comment by fklemme** [comment]
Very good, thanks a lot! That also fixed a problem where a few newer cards were shown uncategorized in my deck listing. Now everything looks good. :)
