### ISSUE TITLE
Status Page Not Working

### ISSUE THREAD

**Issue by Peabo83** [mpaulweeks/mtgify#16]
This is a fantastic repo, being able to include it on a page with a single js file is great.

I ran into an issue on a page I'm working on, it's the same issue outlined in: https://github.com/mpaulweeks/mtgify/issues/8

I went to your status page ( https://mpaulweeks.github.io/mtgify/status/ ) and that page is throwing the CORS error for me as well. I appreciate any help you could provide!

**Comment by mpaulweeks** [comment]
Thank you for bringing this to my attention. It's probably more issues with my hosting provider not attaching the headers correctly.

I will move hosting providers this weekend and update this issue with progress.

**Comment by mpaulweeks** [comment]
@Peabo83 I have migrated to a new host with new configs. Please refresh the page you're working on and let me know if it works now.

**Comment by Peabo83** [comment]
Working like a charm once again, thanks for such a quick response!
