### ISSUE TITLE
Support for ZNR/CMR Spoiled Cards

### ISSUE THREAD

**Issue by ArtSabintsev** [mpaulweeks/mtgify#18]
Hi!

On the side, I run [CommanderSpellbook.com](https://CommanderSpellbook.com), which is an EDH Combo Database. We just switched over to using your tool, pointing the data-source to Scryfall (see here for [my implementation](https://github.com/ArtSabintsev/CommanderSpellbook/blob/master/index.html#L49)). I am pinging you today because we see an issue with [spoiled cards](https://commanderspellbook.com/?status=spoiled), like `Alena, Kessig Trapper`, not appearing on hover. However, if you click on the link it loads just fine. 

I'm wondering if this is a mtgjson issue. If so, is there a way to switch the on-hover data source to use Scryfall's API for fetching images? 

I haven't checked out the source code, but wanted to ping you to let you know.

Thanks!

(Our Discord can be found here - feel free to ping any of the Admins or Mods: https://discord.gg/DkAyVJG)

**Comment by mpaulweeks** [comment]
Hello! Glad you like mtgify.

You are correct, it is an mtgjson thing. I will look into a Scryfall workaround for spoilers this weekend.

Cool site! :)

**Comment by ArtSabintsev** [comment]
@mpaulweeks Thank you so much! I appreciate it!

**Comment by ArtSabintsev** [comment]
So I was perusing MTGJSON, and I saw they have spoiled Cards from CMR (Commander Legends) already available: https://mtgjson.com/downloads/all-sets/

**Comment by mpaulweeks** [comment]
First, thank you again for bringing this to my attention.

It appears MTGJSON's API had changed in a way that broke my tool. I have fixed the problem and it should be compatible with future sets going forward.

However, it appears that some new cards like Rin and Seri are missing multiverse IDs. My tool currently relies on these to build links and images for gatherer.

I can look into moving off gatherer permanently, or find a workaround, but that's a major undertaking and I'm currently recovering from surgery. I can hope to get to it some time next month, though no promises.

You are always welcome to submit a pull request. :)

**Comment by ArtSabintsev** [comment]
Hey! Thanks so much for the quick turnaround time! I hope you recover quickly from your surgery!

So, question for you - if I set Scryfall as the default in the config, is gatherer still used? 

I don't see the improvements to spoiled cards live on my end, except that images (for old cards) seem to load faster. 

Thanks for following up!

**Comment by einstein95** [comment]
Neither mtgjson not Scryfall had the Gatherer ID set for Rin and Seri (despite being out for 2 months), but I have submitted a bug report for the latter to add it in.

For future notes, the Gatherer link is https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=489663

**Comment by ArtSabintsev** [comment]
Thank you for following up!
