### ISSUE TITLE
M21 Buy-a-Box promo missing

### ISSUE THREAD

**Issue by einstein95** [mpaulweeks/mtgify#19]
Card is `Rin and Seri, Inseparable`
https://scryfall.com/card/m21/278/rin-and-seri-inseparable

**Comment by ArtSabintsev** [comment]
@mpaulweeks This is another issue we're seeing on https://CommanderSpellbook.com. Here's an example of one such combo: https://CommanderSpellbook.com/?id=3203

**Comment by mpaulweeks** [comment]
See https://github.com/mpaulweeks/mtgify/issues/18#issuecomment-685193262

**Comment by mpaulweeks** [comment]
I believe this was determined to be an underlying issue with MTGJSON, and that is now resolved?

Closing for now. Please feel free to re-open if it happens again.
