### ISSUE TITLE
Strixhaven cards not working

### ISSUE THREAD

**Issue by Greven145** [mpaulweeks/mtgify#24]
As per your last issue comment, just wanted to let you know it seems the strixhaven cards aren't updated. I'd be happy to look at the updater code that's not working and supply a pull request if that would help

**Comment by mpaulweeks** [comment]
Should be fixed now!

To explain myself better: the updater code works fine! I just need to run it manually. I used to run it every couple of hours via cron, but I suspect the card data has gotten so huge that the cron job runs out of memory and dies. It's hard to debug cron jobs :/

Please let me know if you run into any further issues.
