### ISSUE TITLE
CORS policy is blocking access to https://mtgify.org/json/version.json

### ISSUE THREAD

**Issue by Gikkman** [mpaulweeks/mtgify#8]
Hi.

I really like the idea behind this library, so I thought I'd try to give it a quick swing. I created a really small page, and tried to render an auto-card of Counterspell, but the page just showed the card name. When I explored the page source, is saw it had generated a link element, but the link was empty:

```
<body>
    <auto-card data-autocard-id="0">
      <a target="_blank">Counterspell</a>
   </auto-card>
</body>
```

Checking the source further, I saw that the console gave me the following 

> Access to fetch at 'https://mtgify.org/json/version.json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS 

```
Uncaught (in promise) TypeError: Failed to fetch
Promise.then (async)
(anonymous) @ autocard.js:1
e.exports @ autocard.js:1
10../AutoCard @ autocard.js:1
o @ autocard.js:1
t @ autocard.js:1
(anonymous) @ autocard.js:1
```
I am not 100% sure what is going on, but my quick googling suggests that the browser blocks the autocard script, which comes from an external source, to make a request for another external source.

I'm not sure if I need to add something on my end to make this all work. For reference, here is my HTML document:

```
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MtG</title>

    <link rel="stylesheet" href="https://mtgify.org/dist/autocard.css" />
    <script src="https://mtgify.org/dist/autocard.js"></script>
</head>
<body>
    <auto-card>Counterspell</auto-card>
</body>
</html>
```

**Comment by mpaulweeks** [comment]
Thank you for bringing this to my attention and providing thorough documentation!

I've been having some CORS issues lately with my Cloudfront setup, wherein the nightly cronjob that updates the card data will...convince Cloudfront to no longer serve the JSON files with the proper headers??? A more reliable fix for that is still in the works.

In the meantime, I have confirmed that the CORS are [currently working](https://mpaulweeks.github.io/mtgify/status/) and your example code runs fine. Please re-open if you have any further issues.
